version: "3"
services:
  drivent-back:
    container_name: drivent-back
    build: . #Dockerfile do node se encontra na pasta atual
    ports:
      - 4000:4002
    depends_on:
      - drivent-db # só sobe quando o postgres tiver no ar
      - drivent-cache
    env_file:
      - .env.development #configurar DATABASE_URL
    volumes:
      - .:/drivent-back
    networks:
      - drivent-network

  drivent-cache:
    container_name: drivent-cache
    image: redis:latest
    restart: always
    ports:
      - 9736:6379
    networks:
      - drivent-network

  drivent-db:
    image: postgres:13
    container_name: drivent-db
    restart: always #container reinicia se morrer
    ports:
      - 2345:5432
    env_file:
      - .env.development #configurar POSTGRES_USER, POSTGRES_PASSWORD e POSTGRES_DB
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - drivent-network

volumes:
  postgres:


networks:
  drivent-network:
    driver: bridge
